# Generated by Django 5.1.5 on 2025-01-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
